# -*- coding: utf-8 -*-
"""Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbGJxrqxThrYelaqFPCuak71KhMjzlDk
"""

import pandas as pd
from numpy import NaN
from pandas._libs.missing import NA

from bs4 import BeautifulSoup
import requests
import json

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in the root directory
!mkdir -p "/content/drive/My Drive/My Folder"

#Import datasets
df_news=pd.read_csv('/content/drive/My Drive/My Folder/cleaned_full_dataset.csv', encoding_errors='ignore')

df_news.isnull().sum()

#Remove unnamed columns/remove columns from index 16 to 178
df_news.drop(df_news.iloc[:, 16:179], inplace=True, axis=1)

#Remove unnamed 0
df_news=df_news.drop(['Unnamed: 0'], axis=1)

df_news

#Find rows where title is blank
df_title_blank=df_news[df_news['title']==' ']

df_title_blank['Publisher'].unique()
df_title_blank

#News from New Dawn Liberia has missing titles

"""Rescraping news titles from New Dawn Liberia"""

#Get all the indexes
index_missing_titles=list(df_title_blank.index)
index_missing_titles

#Update the title in df_news
for index, row in df_news.iterrows():
  if index in index_missing_titles:
    x=requests.get(row['link'])
    soup=BeautifulSoup(x.text, 'html.parser')
    title=soup.body.find(name='h1', attrs={'class': 'post-title entry-title'}).get_text()
    df_news.at[index, 'title']=title

df_news.isnull().sum()

"""title"""

#Find records with nan title
df_news[df_news['title'].isna()]

#3139 3140

#get record 3139 record 3140 and update title
df_news.at[3139, 'title']='EU Congratulates President-Elect George Weah On His Victory'
df_news.at[3140, 'title']='GNN-Liberia Wishes All Its Browsing Public A Prosperous And Happy New Year'

df_news.isnull().sum()

#save to csv
df_news_ori=df_news[['title', 'content', 'date', 'Publisher', 'link', 'Label', 'day', 'month', 'year']]
df_news_ori.to_csv('/content/drive/My Drive/My Folder/full_dataset_collected.csv')

df_news_ori

"""Text Cleaning"""

import string
import nltk
import re
import unicodedata
import lxml.html
import lxml.html.clean
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

#Import csv file of the full original dataset
df_news_ori=pd.read_csv('/content/drive/My Drive/My Folder/full_dataset_collected.csv', encoding='latin-1')

#Function: removve html tags
def remove_htmltags(text):
  doc=lxml.html.fromstring(text)
  cleaner=lxml.html.clean.Cleaner(style=True)
  doc=cleaner.clean_html(doc)
  text=doc.text_content()
  return text

#Function: remove numbers/digits
def remove_numbers(s):
  s=re.sub(r'\d+', '', str(s))
  return s

#Function remove accented characters
def remove_ac(text):
  text=re.sub('[¼ë½âª¹ºµ³²]','',text)
  return text

#Function: remove special characters
def remove_sc(text):
  removal="Ã¢â\x82¬Å\x93"+"Ã¢â\x82¬"+"\x84"+"\x83"+"\x80\x9c"+"Â\x9aÂ"+"Â\x9aÂ\x9eÂ"+"\x85"+"\\x9"+"Ë"+"©"+"ª"+"µ"+"³"+"²"+"¼"+"½"
  text=''.join(w for w in text if w not in removal)
  return text

#Function: remove punctuation and stopwords // tokenise
def tokenise_text(s):
  p=string.punctuation+'’”'
  s=''.join(ch for ch in s if ch not in p)
  s_tokenised=word_tokenize(s)
  s_cleaned=[w for w in s_tokenised if w.lower() not in stopwords.words('english')]
  return s_cleaned

#Function: converse to lowercase
def to_lowercase(words):
    """Convert all characters to lowercase from list of tokenized words"""
    new_words=[]
    for word in words:
      new_word = word.lower()
      new_words.append(new_word)
    return new_words

#Function: lemmatisation
def lemmatise_text(l_tokenised):
  lemmatizer=WordNetLemmatizer()
  s_lemmatised=[lemmatizer.lemmatize(word) for word in l_tokenised]
  lemmatised_text=' '.join(s_lemmatised)
  return lemmatised_text

s1=remove_htmltags(df_news_ori.loc[23223, 'content'])

s2=remove_sc(s1)

s2

s3=remove_numbers(s2)

s3

s4=tokenise_text(s3)

s5=to_lowercase(s4)

s6=lemmatise_text(s5)

#clean text
df_news_ori['content_cleaned']=''
for index, r in df_news_ori.iterrows():
  s1=remove_htmltags(r['content'])
  s2=remove_sc(s1)
  s3=remove_numbers(s2)
  df_news_ori.at[index,'content_cleaned']=s3

df_news_ori

#Tokenisation
df_news_ori['content_tokenised']=''
for index, r in df_news_ori.iterrows():
  df_news_ori.at[index,'content_tokenised']=tokenise_text(r['content_cleaned'])

df_news_ori

#Conversion to lowercase
df_news_ori['content_lowercase']=''
for index, r in df_news_ori.iterrows():
  df_news_ori.at[index,'content_lowercase']=to_lowercase(r['content_tokenised'])

df_news_ori

#Lemmatisation
df_news_ori['content_lemmatised']=''
for index, r in df_news_ori.iterrows():
  df_news_ori.at[index,'content_lemmatised']=lemmatise_text(r['content_lowercase'])

df_news_ori

#save to csv
df_news_ori.to_csv('/content/drive/My Drive/My Folder/updated_full_dataset.csv')

#df_news[df_news['content_cleaned']=='']
df_news_ori=df_news_ori.drop(df_news_ori[df_news_ori['content_cleaned']==''].index)
df_news_ori=df_news_ori.drop(df_news_ori[df_news_ori['content_cleaned']==' '].index)

#Remove rows that contain missing data
for index, r in df_news_ori.iterrows():
  if len(r['content_tokenised'])==0:
    df_news_ori=df_news_ori.drop(index)

"""# EDA"""

import plotly.express as px
import plotly.graph_objects as go
import nltk
nltk.download('averaged_perceptron_tagger')
from collections import Counter

df_news=df_news_ori

df_news

#remove unnamed columns
#Remove unnamed 0
df_news=df_news.drop(['Unnamed: 0'], axis=1)

"""News Collection Count by Years"""

#Visualise the news count by year
date_count=df_news['year'].value_counts()
fig=px.histogram(df_news, x='year', title='News Count by Year', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Publication Year').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

#Ratio of fake and real news
r_real=round((df_news['Label'].value_counts()[1])/len(df_news), 3)
r_fake=round((df_news['Label'].value_counts()[0])/len(df_news), 3)
print('The ratio of fake and real news: \n')
print('Real news:{}\nFake news:{}'.format(r_real, r_fake))

#Visualise the number of fake and real news
#label_count=df_news['Label (Fake-0| True-1)'].value_counts()
fig=px.histogram(df_news, x='Label', title='Distribution of fake and factual news', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(type='category', title='News Label').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

#Visualise news lenght count
df_news['content_length']=''
for index, r in df_news.iterrows():
  df_news.at[index,'content_length']=len(r['content_cleaned'])

fig=px.histogram(df_news, x='content_length', title='News Text Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Text length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

#calculation the number of words and the average length of words
df_news['word_count']=''
df_news['aver_word_length']=''

for index, r in df_news.iterrows():
  words=r['content_cleaned'].split()
  df_news.at[index, 'word_count']=len(words)
  df_news.at[index,'aver_word_length']=sum(len(word) for word in words)/len(words)

fig=px.histogram(df_news, x='word_count', title='The number of words', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

#visualisation
fig=px.histogram(df_news, x='aver_word_length', title='Average Word Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

df_news

#Save to csv
df_news.to_csv("/content/drive/My Drive/My Folder/detailed_full_dataset.csv")

df_dataset_calculation=df_news[['Label','year','content_length','word_count','aver_word_length']]
df_dataset_calculation
df_dataset_calculation.to_csv("/content/drive/My Drive/My Folder/dataset_calculation.csv")

"""Word Cloud for fake news"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

df_news.loc[0]['content_cleaned']

input=''
for index, row in df_news.iterrows():
  if row['Label']==0:
    input=input+row['content_lemmatised']

#Creating empty WordCloud object and generating actual WordCloud.
wordcloud=WordCloud().generate(input)

#Display the word cloud
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""POS Tag Counts"""

def get_post_tags_list(tokenised_text):
  all_pos_tags=[]
  for word in tokenised_text:
    pos_tag=nltk.pos_tag([word])[0][1]
    all_pos_tags.append(pos_tag)
  return all_pos_tags

#Get pos_tag of all fake news
pos_tag_fake=[]
pos_tag_real=[]
for index, r in df_news.iterrows():
  if r['Label']==0:
    for w in r['content_tokenised']:
      pos_tag_f=nltk.pos_tag([w])
      pos_tag_fake.append(pos_tag_f)
  if r['Label']==1:
    for w in r['content_tokenised']:
      pos_tag_r=nltk.pos_tag([w])
      pos_tag_real.append(pos_tag_r)

#Function: count the occurrence of different tags in both fake and real news dataset
def get_pos_tag_count(pos_tag_list):
  tags=[]
  from collections import Counter
  for item in pos_tag_list:
    tags.append(item[0][1])
  tag_counts=Counter(tags)
  return tag_counts

#Function: count the occurrence of different words in both fake and real news dataset
def get_word_count(pos_tag_list):
  words=[]
  from collections import Counter
  for item in pos_tag_list:
    words.append(item[0][0])
  word_counts=Counter(words)
  return word_counts

"""word frequency in fake news"""

df_word_fake=pd.DataFrame(list(get_word_count(pos_tag_fake).items()), columns=['word', 'frequency'])
df_word_fake['frequency_ratio']=100*(df_word_fake['frequency']/sum(df_word_fake['frequency']))
df_word_fake['news_category']=0
df_word_fake

df_word_fake.to_csv("/content/drive/My Drive/My Folder/word_freq_fake.csv")

"""word frequency in real news"""

df_word_real=pd.DataFrame(list(get_word_count(pos_tag_real).items()), columns=['word', 'frequency'])
df_word_real['frequency_ratio']=100*(df_word_real['frequency']/sum(df_word_real['frequency']))
df_word_real['news_category']=1
df_word_real

df_word_fake.to_csv("/content/drive/My Drive/My Folder/word_freq_real.csv")

#Concatnate two dataframes
df_word=pd.concat([df_word_real, df_word_fake])

df_word

#Visualise the most frequent words in fake news
fig=px.histogram(df_word_fake[df_word_fake['frequency_ratio']>0.01], x='word', y='frequency_ratio', title='Word Frequency in Fake News')
#fig=px.pie(df_word_fake[df_word_fake['frequency_ratio']>0.45], names='word', values='frequency_ratio', title='Word Frequency in Fake News')
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(xaxis={'categoryorder':'total descending'}, width=1400, height=500)
fig.show()

#Visualise the most frequent words in real news
fig=px.histogram(df_word_real[df_word_real['frequency_ratio']>0.01], x='word', y='frequency_ratio', title='Word Frequency in Fake News')
#fig=px.pie(df_word_real[df_word_real['frequency_ratio']>0.37], names='word', values='frequency_ratio', title='Word Frequency in Real News')
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(xaxis={'categoryorder':'total descending'}, width=1400, height=500)
fig.show()

df_word_real.to_csv("/content/drive/My Drive/My Folder/word_freq_real.csv")

"""pos tag in fake news"""

df_pos_tag_fake=pd.DataFrame(list(get_pos_tag_count(pos_tag_fake).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_fake['frequency_ratio']=100*(df_pos_tag_fake['frequency']/sum(df_pos_tag_fake['frequency']))
df_pos_tag_fake['news_category']=0
df_pos_tag_fake

"""pos tag in real news"""

df_pos_tag_real=pd.DataFrame(list(get_pos_tag_count(pos_tag_real).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_real['frequency_ratio']=100*(df_pos_tag_real['frequency']/sum(df_pos_tag_real['frequency']))
df_pos_tag_real['news_category']=1
df_pos_tag_real

#Concatenate two DataFrames
df_pos_tag=pd.concat([df_pos_tag_real, df_pos_tag_fake])
df_pos_tag

#save to csv
df_pos_tag.to_csv('/content/drive/My Drive/My Folder/pos_tag.csv')

#Get the most frequent proper nouns in real news
nnpwords_real=[]
for item in pos_tag_real:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_real.append(item[0][0])
nnp_real=Counter(nnpwords_real)
nnp_real.most_common(100)

#Save to dataframe
df_nnp_real=pd.DataFrame(nnp_real.most_common(212))
df_nnp_real['news_category']=1
df_nnp_real=df_nnp_real.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_real['frequency_ratio']=(df_nnp_real['frequency']/len(nnpwords_real))*100

#Drop month proper nouns
import calendar
month_name=list(calendar.month_name)[1::]
df_nnp_real=df_nnp_real.loc[~df_nnp_real['NNP'].isin(month_name)]

df_nnp_real

#Get the most frequent proper nouns in fake news
nnpwords_fake=[]
for item in pos_tag_fake:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_fake.append(item[0][0])
nnp_fake=Counter(nnpwords_fake)
nnp_fake.most_common(100)

#Save to dataframe
df_nnp_fake=pd.DataFrame(nnp_fake.most_common(212))
df_nnp_fake['news_category']=0
df_nnp_fake=df_nnp_fake.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_fake['frequency_ratio']=(-df_nnp_fake['frequency']/len(nnpwords_fake))*100

#Drop month proper nouns
df_nnp_fake=df_nnp_fake.loc[~df_nnp_fake['NNP'].isin(month_name)]

df_nnp_fake

#Concatenate 2 dataframes
df_nnp=pd.concat([df_nnp_real, df_nnp_fake])
df_nnp

#Reset index
df_nnp=df_nnp.reset_index()
df_nnp=df_nnp.drop(['index'], axis=1)
df_nnp

#Save to csv
df_nnp.to_csv("/content/drive/My Drive/My Folder/nnp_200.csv")

"""**TF-IDF**

"""

print("The number of words in fake news is: " +str(len(df_word_fake)))
print("The number of words in real news is: " +str(len(df_word_real)))
print("There are {} words with frequency >= 0.05 in fake news.".format(len(df_word_fake[df_word_fake['frequency_ratio']>=0.01])))
print("There are {} words with frequency >= 0.05 in real news.".format(len(df_word_real[df_word_real['frequency_ratio']>=0.01])))

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(min_df=0.1, stop_words='english')

df_news_0=[df_news.loc[0]['content_lemmatised'],'']

response=vectorizer.fit_transform(df_news_0)
df_tfidf_sklearn=pd.DataFrame(response.toarray(),columns=vectorizer.get_feature_names_out())
df_tfidf_sklearn.loc[0]

response=vectorizer.fit_transform(list(df_news['content_lemmatised']))
df_tfidf_sklearn=pd.DataFrame(response.toarray(),columns=vectorizer.get_feature_names_out())
df_tfidf_sklearn

df_tfidf_sklearn.to_csv("/content/drive/My Drive/My Folder/tf_idf_matrix.csv")

df_tfidf_sklearn=pd.read_csv("/content/drive/My Drive/My Folder/tf_idf_matrix.csv")

"""Deal with imbalanced dataset

Oversampling with SMOTE
"""

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

#Split the whole dataset
X=df_tfidf_sklearn
y=df_news['Label']

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=0)

#The size of training set and test set
print(X_train.shape, X_test.shape)

#Oversample by SMOTE method
os=SMOTE(random_state=2)
columns=X_train.columns
os_data_X,os_data_y=os.fit_resample(X_train, y_train)
os_data_y=os_data_y.to_frame()

#Check the numbers of our data
print("length of oversampled data is ",len(os_data_X))
print("Number of fake news in oversampled data is ",len(os_data_y[os_data_y['Label']==0]))
print("Number of real news in oversampled data is ",len(os_data_y[os_data_y['Label']==1]))
print("Proportion of fake news in oversampled data is ",len(os_data_y[os_data_y['Label']==0])/len(os_data_X))
print("Proportion of real news in oversampled data is ",len(os_data_y[os_data_y['Label']==1])/len(os_data_X))

#Join X and y
df_smote_data=pd.concat([os_data_X, os_data_y], axis=1)
#df_smote_data=df_os_data.drop(["Unnamed: 0"], axis=1)
df_smote_data

#save to csv
df_smote_data.to_csv("/content/drive/My Drive/My Folder/smote_sample.csv")

"""Unersampling by Near Miss"""

from imblearn.under_sampling import NearMiss
nr=NearMiss()

nm_data_X, nm_data_y=nr.fit_resample(X_train, y_train)
nm_data_y=nm_data_y.to_frame()

#Check the numbers of our data
print("length of undersampled data is ",len(nm_data_X))
print("Number of fake news in undersampled data is ",len(nm_data_y[nm_data_y['Label']==0]))
print("Number of real news in undersampled data is ",len(nm_data_y[nm_data_y['Label']==1]))
print("Proportion of fake news in undersampled data is ",len(nm_data_y[nm_data_y['Label']==0])/len(nm_data_X))
print("Proportion of real news in undersampled data is ",len(nm_data_y[nm_data_y['Label']==1])/len(nm_data_X))

#Join X and y
df_nm_data=pd.concat([nm_data_X, nm_data_y], axis=1)
#df_nm_data=df_nm_data.drop(["Unnamed: 0"], axis=1)
df_nm_data

#save to csv
df_nm_data.to_csv("/content/drive/My Drive/My Folder/nm_sample.csv")

"""# Model implementation

Logic regression
"""

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report

#Fit logic regression model before oversampling
logreg=LogisticRegression()
logreg.fit(X_train, y_train)
y_predictions=logreg.predict(X_test)

from sklearn.metrics import confusion_matrix
cfm=confusion_matrix(y_test, y_predictions)
print(cfm)

print(classification_report(y_test, y_predictions))

#Fit logic regression model after oversampling
logreg=LogisticRegression()
logreg.fit(os_data_X, os_data_y['Label'])
os_y_predictions=logreg.predict(X_test)

cfm=confusion_matrix(y_test, os_y_predictions)
print(cfm)

print(classification_report(y_test, os_y_predictions))

logreg.predict_proba(X_test)[:,1]

logreg.predict_proba(X_test)[:,0]

"""Naive Bayes Classifier"""

from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB()
MNB.fit(os_data_X, os_data_y['Label'])
y_predictions=MNB.predict(X_test)

print(classification_report(y_test, y_predictions))

"""Random Forest Classifier"""

from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf=RandomForestRegressor(random_state=0)
# Train the model on training data
rf.fit(os_data_X, os_data_y['Label'])
y_predicitons=rf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predictions)

"""SVM"""

from sklearn import svm
clf=svm.SVC(kernel='linear')
clf.fit(os_data_X, os_data_y['Label'])
y_predictions=clf.predict(X_test)

accuracy_score(y_test, y_predictions)

"""Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier

gbc=GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
gbc.fit(os_data_X, os_data_y['Label'])

y_predictions=gbc.predict(X_test)
gbc.score(X_test, y_test)