# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kgTGgNYX0Y76EOB0TQoCc78aH9Quoam
"""

import pandas as pd

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in the root directory
!mkdir -p "/content/drive/My Drive/My Folder"

#Import datasets
df_news=pd.read_csv('/content/drive/My Drive/My Folder/updated_full_dataset.csv', encoding_errors='ignore')

#Remove rows with NaN
df_news=df_news.dropna(axis=0)
df_news.isnull().sum()

#Remove unnamed columns
df_news=df_news.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)

df_news

"""EDA"""

import plotly.express as px
import plotly.graph_objects as go
import nltk
nltk.download('averaged_perceptron_tagger')
from collections import Counter

df_news.dtypes

"""News Collection Count by Years"""

#Visualise the news count by year
date_count=df_news['year'].value_counts()
fig=px.histogram(df_news, x='year', title='News Count by Year', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Publication Year').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

"""Distribution of fake and real news"""

#Ratio of fake and real news
r_real=round((df_news['Label'].value_counts()[1])/len(df_news), 3)
r_fake=round((df_news['Label'].value_counts()[0])/len(df_news), 3)
print('The ratio of fake and real news: \n')
print('Real news:{}\nFake news:{}'.format(r_real, r_fake))

#Visualise the number of fake and real news
#label_count=df_news['Label (Fake-0| True-1)'].value_counts()
fig=px.histogram(df_news, x='Label', title='Distribution of fake and factual news', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(type='category', title='News Label').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

"""Text Length"""

#Visualise news lenght count
df_news['content_length']=''
for index, r in df_news.iterrows():
  df_news.at[index,'content_length']=len(r['content_cleaned'])

fig=px.histogram(df_news, x='content_length', title='News Text Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Text length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

"""Average Word Length"""

#calculation
df_news['aver_word_length']=''
for index, r in df_news.iterrows():
  words=r['content_cleaned'].split()
  df_news.at[index,'aver_word_length']=sum(len(word) for word in words)/len(words)

#visualisation
fig=px.histogram(df_news, x='aver_word_length', title='Average Word Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

#Save to csv
df_news.to_csv("/content/drive/My Drive/My Folder/detailed_full_dataset.csv")

"""POS Tag Counts"""

def get_post_tags_list(tokenised_text):
  all_pos_tags=[]
  for word in tokenised_text:
    pos_tag=nltk.pos_tag([word])[0][1]
    all_pos_tags.append(pos_tag)
  return all_pos_tags

df_news.loc[23223]['content_tokenised']

remove_ac(df_news.loc[23223]['content_tokenised'])

#update tokenised content
for index, r in df_news.iterrows():
  t1=r['content_tokenised'].replace("['", "")
  t1=t1.replace("']", "")
  t1=t1.split("', '")
  df_news.at[index,'content_tokenised']=t1

df_news

df_news.loc[31460]['content_tokenised']

for w in df_news.loc[0]['content_lemmatised'].split(" "):
  print(nltk.pos_tag([w]))

#Get pos_tag of all fake news
pos_tag_fake=[]
pos_tag_real=[]
for index, r in df_news.iterrows():
  if r['Label']==0:
    for w in r['content_lemmatised'].split(" "):
      pos_tag_f=nltk.pos_tag([w])
      pos_tag_fake.append(pos_tag_f)
  if r['Label']==1:
    for w in r['content_lemmatised'].split(" "):
      pos_tag_r=nltk.pos_tag([w])
      pos_tag_real.append(pos_tag_r)

pos_tag_real

nnpwords_real=[]
for item in pos_tag_real:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_real.append(item[0][0])
nnp_real=Counter(nnpwords_real)
nnp_real.most_common(100)

nnpwords_fake=[]
for item in pos_tag_fake:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_fake.append(item[0][0])
nnp_fake=Counter(nnpwords_fake)
nnp_fake.most_common(100)

#Save to dataframe
df_nnp_real=pd.DataFrame(nnp_real.most_common(212))
df_nnp_real['news_category']=1
df_nnp_real=df_nnp_real.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_real['frequency_ratio']=(df_nnp_real['frequency']/len(nnpwords_real))*100

#Drop month proper nouns
import calendar
month_name=list(calendar.month_name)[1::]
df_nnp_real=df_nnp_real.loc[~df_nnp_real['NNP'].isin(month_name)]

df_nnp_real

df_nnp_fake=pd.DataFrame(nnp_fake.most_common(212))
df_nnp_fake['news_category']=0
df_nnp_fake=df_nnp_fake.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_fake['frequency_ratio']=(-df_nnp_fake['frequency']/len(nnpwords_fake))*100

#Drop month proper nouns
df_nnp_fake=df_nnp_fake.loc[~df_nnp_fake['NNP'].isin(month_name)]

df_nnp_fake

#Concatenate 2 dataframes
df_nnp=pd.concat([df_nnp_real, df_nnp_fake])
df_nnp

#Reset index
df_nnp=df_nnp.reset_index()
df_nnp=df_nnp.drop(['index'], axis=1)
df_nnp

#Save to csv
df_nnp.to_csv("/content/drive/My Drive/My Folder/nnp_200.csv")

#Function: count the occurrence of different tags in both fake and real news dataset
def get_pos_tag_count(pos_tag_list):
  tags=[]
  from collections import Counter
  for item in pos_tag_list:
    tags.append(item[0][1])
  tag_counts=Counter(tags)
  return tag_counts

list(get_pos_tag_count(pos_tag_fake).items())

get_pos_tag_count(pos_tag_real)

df_pos_tag_fake=pd.DataFrame(list(get_pos_tag_count(pos_tag_fake).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_fake['frequency_ratio']=100*(df_pos_tag_fake['frequency']/sum(df_pos_tag_fake['frequency']))
df_pos_tag_fake['news_category']=0
df_pos_tag_fake

df_pos_tag_real=pd.DataFrame(list(get_pos_tag_count(pos_tag_real).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_real['frequency_ratio']=100*(df_pos_tag_real['frequency']/sum(df_pos_tag_real['frequency']))
df_pos_tag_real['news_category']=1
df_pos_tag_real

#Concatenate two DataFrames
df_pos_tag=pd.concat([df_pos_tag_real, df_pos_tag_fake])
df_pos_tag

#save to csv
df_pos_tag.to_csv('/content/drive/My Drive/My Folder/pos_tag.csv')

df_pos_tag=pd.read_csv('/content/drive/My Drive/My Folder/pos_tag.csv')

df_pos_tag_vis=df_pos_tag[df_pos_tag['frequency_ratio']>=1.3]

for index, r in df_pos_tag_vis.iterrows():
  if r['pos_tag']=='JJ':
    df_pos_tag_vis.at[index, 'pos_tag']='adjective'
  if r['pos_tag']=='NN':
    df_pos_tag_vis.at[index, 'pos_tag']='noun, singular'
  if r['pos_tag']=='NNS':
    df_pos_tag_vis.at[index, 'pos_tag']='noun, plural'
  if r['pos_tag']=='NNP':
    df_pos_tag_vis.at[index, 'pos_tag']='proper noun, singular'
  if r['pos_tag']=='VBN':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, past participler'
  if r['pos_tag']=='VBG':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, gerund'
  if r['pos_tag']=='RB':
    df_pos_tag_vis.at[index, 'pos_tag']='adverb'
  if r['pos_tag']=='VBD':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, past tense'
  if r['pos_tag']=='VB':
    df_pos_tag_vis.at[index, 'pos_tag']='verb'

#Visualisation
fig=px.histogram(df_pos_tag_vis, x='pos_tag', y='frequency_ratio', title='POS Tagging Frequency in Fake and Real News', barmode='group', color='news_category', color_discrete_sequence=px.colors.qualitative.Vivid)
fig.update_xaxes(title='POS Tagging').update_yaxes(title='Frequency')
fig.update_layout(xaxis={'categoryorder':'total descending'}, width=1400, height=500)
fig.show()

"""Word frequency in fake news

"""

df_word_fre_fake=pd.read_csv('/content/drive/My Drive/My Folder/word_freq_fake.csv')

df_word_fre_fake

from wordcloud import WordCloud
import matplotlib.pyplot as plt

Creating empty WordCloud object and generating actual WordCloud.
wordcloud = WordCloud().generate(input)