# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3LfZR6LEdWKWmoszRUPoEm7-NMdW4FJ
"""

from bs4 import BeautifulSoup
import requests

import json
import pandas as pd

import lxml.html as lh
import lxml.html.clean as lhclean

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in the root directory
!mkdir -p "/content/drive/My Drive/My Folder"

"""Data Scraping from Front Page Africa (Factual News)"""

from requests.api import request

URL='https://frontpageafricaonline.com/category/'
Categories=['news/people-innovation', 'politics', 'sports', 'county-news']
news_links=[]
Content=[]
Titles=[]
Authors=[]
Dates=[]

for ca in Categories:
  for p in range(1,15):
    x=requests.get(URL+ca+'/page/'+str(p)+'/')
    soup=BeautifulSoup(x.text, 'html.parser')
    links=soup.body.find_all(name='h2', attrs={'class':'is-title post-title'})
    for link in links:
      link=link.find('a').get('href')
      x0=requests.get(link)
      soup=BeautifulSoup(x0.text, 'html.parser')
      #Extract features of news
      i=soup.body.find(name='script', attrs={'type':'application/ld+json'})
      if i is not None:
        t=i.get_text()
        if 'headline' in t:
          #Get Content
          c=''.join(line.get_text() for line in soup.findAll('p'))
          Content.append(c)
          info=json.loads(t)
          news_links.append(info['url'])
          Titles.append(info['headline'])
          Authors.append(info['author']['name'])
          Dates.append(info['datePublished'].split('T')[0])

#Save in a dictionary
FPA_dic={'Title':Titles, 'Content':Content, 'Publication_date':Dates, 'Link':news_links, 'Author':Authors}

#Save to csv
df_FPA=pd.DataFrame.from_dict(FPA_dic)

#Convert date data format
df_FPA['Publication_date']=df_FPA['Publication_date'].astype('datetime64[ns]')
df_FPA['Publication_date']=df_FPA['Publication_date'].dt.strftime("%d/%m/%Y")

df_FPA

df_FPA['Label']=1
df_FPA['Publisher']='Front Page Africa'

df_FPA.to_csv('/content/drive/My Drive/My Folder/FPA_label_data.csv')

"""Data Scraping from ICIR"""

#Add author for df_icir
df_icir=pd.read_csv('/content/drive/My Drive/My Folder/ICIR_label_data.csv', encoding_errors='ignore')
df_icir=df_icir.dropna(axis=1)

df_icir

author_names=[]
for index, row in df_icir.iterrows():
  x=requests.get(row['Link'])
  soup=BeautifulSoup(x.text, 'html.parser')
  author_name=soup.body.find(name='a',attrs={'class': 'tdb-author-name'}).get_text()
  author_names.append(author_name)

df_icir['Author']=author_names
df_icir

df_icir=df_icir.rename(columns={'title':'Title', 'label':'Label (Fake-0| True-1)', 'content':'Content', 'date':'Publication_date', 'url':'Link'})

#Convert date data format
df_icir['Publication_date']=df_icir['Publication_date'].astype('datetime64[ns]')
df_icir['Publication_date']=df_icir['Publication_date'].dt.strftime("%d/%m/%Y")

#Transform labels to 0/1 in df_icir
for index, r in df_icir.iterrows():
  if r['Label (Fake-0| True-1)']==False:
    df_icir.at[index,'Label (Fake-0| True-1)']=0
  if r['Label (Fake-0| True-1)']==True:
    df_icir.at[index,'Label (Fake-0| True-1)']=1

df_icir

#Save to csv
df_icir.to_csv('/content/drive/My Drive/My Folder/ICIR_label_data.csv')

"""Data Scraping from GhanaFact"""

#Function
def content_extraction(page_url):
  titles=[]
  publication_dates=[]
  contents=[]
  news_links=[]
  x=requests.get(page_url)
  soup=BeautifulSoup(x.text, 'html.parser')
  links=soup.body.find_all(name='h3', attrs={'class':'elementor-post__title'})
  for link in links:
    link=link.find('a').get('href')
    news_links.append(link)
    x1=requests.get(link)
    soup1=BeautifulSoup(x1.text, 'html.parser')
    #Title
    title=soup1.body.find(name='h1', attrs={'class':'elementor-heading-title elementor-size-default'}).get_text()
    titles.append(title)
    #Date
    pd=soup1.body.find(name='span', attrs={'class':'elementor-icon-list-text elementor-post-info__item elementor-post-info__item--type-date'}).get_text()
    pd=pd.strip('/\n')
    pd=pd.strip('/\t')
    publication_dates.append(pd)
    #Content
    c=''.join(line.get_text() for line in soup1.findAll('p'))
    contents.append(c)
  #Store in a dictionary
  news_dic={'Title':titles, 'Content':contents, 'Publication_date':publication_dates, 'Link': news_links}
  return news_dic

from requests.api import request
URL='https://ghanafact.com/category/'
categories=['governance', 'politics', 'economy', 'health', 'environment', 'other-checks', 'deepfakes']

news_links=[]
titles=[]
publication_dates=[]
contents=[]
for c in categories:
  for page in range(1,6):
    page_link=URL+c+'/page/'+str(page)+'/'
    x=requests.get(page_link)
    soup=BeautifulSoup(x.text, 'html.parser')
    links=soup.body.find_all(name='h3', attrs={'class':'elementor-post__title'})
    for link in links:
      link=link.find('a').get('href')
      news_links.append(link)
      x1=requests.get(link)
      soup1=BeautifulSoup(x1.text, 'html.parser')
      #Title
      title=soup1.body.find(name='h1', attrs={'class':'elementor-heading-title elementor-size-default'}).get_text()
      titles.append(title)
      #Date
      pd=soup1.body.find(name='span', attrs={'class':'elementor-icon-list-text elementor-post-info__item elementor-post-info__item--type-date'}).get_text()
      pd=pd.strip('/\n')
      pd=pd.strip('/\t')
      publication_dates.append(pd)
      #Content
      content=''.join(line.get_text() for line in soup1.findAll('p'))
      contents.append(content)

#Store in a dictionary
news_dic={'Title':titles, 'Content':contents, 'Publication_date':publication_dates, 'Link': news_links}

#To dataframe
df_GhanaFact=pd.DataFrame(news_dic)
df_GhanaFact

#Publisher
df_GhanaFact['Publisher']='Ghana Fact'

#Save to csv
df_GhanaFact.to_csv('/content/drive/My Drive/My Folder/GhanaFact_data.csv')

"""Data Scraping from Dubawa"""

#Get all news and store them in dataframe
URL='https://dubawa.org/category/country/liberia/page/'
news_link=[]
news_content=[]
for page in range(1,9):
  x=requests.get(URL+str(page)+'/')
  soup=BeautifulSoup(x.text, 'html.parser')
  links=soup.body.find_all(name='h2', attrs={'class':'post-title'})
  for link in links:
    link=link.find('a').get('href')
    x1=requests.get(link)
    soup1=BeautifulSoup(x1.text, 'html.parser')
    t=soup1.body.find(name='script',attrs={'id': 'tie-schema-json'}).get_text()
    content=json.loads(t)
    news_content.append(content)

news_content_df_1=pd.DataFrame(news_content)

news_content_df_1

#Feature extracted: dateCreated, datePublished, dateModified, headline, url, articleSection, articleBody, publisher

news_content_df_1=news_content_df_1[['datePublished', 'headline', 'url', 'articleSection', 'articleBody', 'author' ,'publisher']]

for index, r in news_content_df_1.iterrows():
  r['publisher']=r['publisher']['name']
  r['author']=r['author']['name']

news_content_df_1

#Remove time from publish date
for index, r in news_content_df_1.iterrows():
  r['datePublished']=r['datePublished'].split('T')[0]

#Change date format
news_content_df_1['datePublished']=news_content_df_1['datePublished'].astype('datetime64[ns]')

news_content_df_1['datePublished']=news_content_df_1['datePublished'].dt.strftime("%d/%m/%Y")

news_content_df_1

#Remove \n \xa0 &amp &nbsp in articleBody
news_content_df_1['articleBody']=news_content_df_1['articleBody'].replace('\xa0','',regex=True)
news_content_df_1['articleBody']=news_content_df_1['articleBody'].replace('\n','',regex=True)
for index, r in news_content_df_1.iterrows():
  doc=lh.fromstring(r['articleBody'])
  cleaner=lhclean.Cleaner(style=True)
  doc=cleaner.clean_html(doc)
  r['articleBody']=doc.text_content()


news_content_df_1

#Create a label column
news_content_df_1['Label']='x'

#Label fake news with 0 by checking its articleSection including 'Fact Check'
indexes=[]
for index, r in news_content_df_1.iterrows():
  if 'Fact Check' in r['articleSection']:
    r['Label']=0
    indexes.append(index)
  else:
    r['Label']=1

print('{} pieces of news have been labelled as fake news'.format(len(indexes)))
news_content_df_1

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in the root directory
!mkdir -p "/content/drive/My Drive/My Folder"

#Save labelled fake news in csv
news_content_df_1.to_csv('/content/drive/My Drive/My Folder/news_collection_Dubawa.csv')